name: xample
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+4

environment:
  sdk: ">=2.15.1 <3.0.0" #Dart SDK 2021-12-20
  flutter: ">=2.8.1"

dependencies:
  cupertino_icons: ^1.0.4
  rae_curvedbottombutton_package:
    path: ../
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^4.3.0
  theme_management:
    git:
      url: https://github.com/RAE-Health/theme_management.git
  theme_mode_widgets:
    git:
      url: https://github.com/RAE-Health/theme_mode_widgets.git
      # url: git@github.com:RAE-Health/theme_mode_widgets.git
  rae_localization_package:
    git:
      url: https://github.com/RAE-Health/rae_localization_package
      # url: git@github.com:RAE-Health/rae_localization_package.git
  rae_asset_package:
    git:
      url: https://github.com/RAE-Health/rae_asset_package.git
      # url: git@github.com:RAE-Health/rae_asset_package.git

dependency_overrides: null

dev_dependencies:
  test:

flutter:
  uses-material-design: true
  generate: true
